"""
LLM-backed Java generation for modernization.

This module consumes modernization prompt packages and delegates generation to a
pluggable backend. The dry-run backend keeps the workflow testable without API
keys; the LangChain backend can call any configured chat model.
"""

import argparse
import ast
import json
import os
import re
from pathlib import Path

try:
    from .prompts import ModernizationPromptGenerator
    from .validation import validate_generated_code
    from ..loader import load_repository
    from ..repository import Repository
except ImportError:
    from repository_intelligence.modernization.prompts import (
        ModernizationPromptGenerator
    )
    from repository_intelligence.modernization.validation import (
        validate_generated_code
    )
    from repository_intelligence.loader import load_repository
    from repository_intelligence.repository import Repository


GENERATION_FORMAT_INSTRUCTIONS = """
Return a JSON object with this shape:
{
  "files": [
    {
      "path": "relative Java source path",
      "language": "java",
      "content": "Java source code"
    }
  ],
  "classes": [
    {
      "name": "Java class name",
      "source_symbol": "Pascal symbol",
      "responsibility": "short summary"
    }
  ],
  "methods": [
    {
      "name": "Java method name",
      "source_symbol": "Pascal method",
      "notes": "mapping notes"
    }
  ],
  "notes": ["important migration notes"],
  "unresolved_items": ["missing information or manual follow-up"]
}
If complete compilable Java cannot be produced from the context, return a
skeleton and list the missing information in unresolved_items.
""".strip()


DEFAULT_LANGCHAIN_GENERATION_MODEL = "google_genai:gemini-3.5-flash"
GOOGLE_GENAI_PACKAGE_HINT = (
    "Gemini generation requires the langchain-google-genai package. "
    "Install it with: pip install langchain-google-genai"
)


class DryRunCodeGenerationBackend:
    """
    Deterministic backend used for local validation.

    It does not call an LLM. It proves that prompt generation, backend
    invocation, and structured result packaging are wired correctly.
    """

    backend_name = "dry_run"

    def generate(self, prompt_package):
        context = prompt_package.get("context", {})
        task = context.get("task", {})
        symbols = context.get("symbols", [])
        primary = symbols[0] if symbols else {}
        class_name = self._java_class_name(primary.get("name") or "Migration")
        package_name = self._package_name(primary.get("file"))

        content = "\n".join([
            f"package {package_name};",
            "",
            "/**",
            " * Dry-run modernization skeleton.",
            f" * Source symbol: {primary.get('name')}",
            f" * Task: {task.get('description')}",
            " */",
            f"public class {class_name} {{",
            "    // Generated by dry-run backend; replace with LLM output.",
            "}"
        ])

        return {
            "backend": self.backend_name,
            "raw_output": content,
            "structured_output": {
                "files": [
                    {
                        "path": (
                            package_name.replace(".", "/")
                            + f"/{class_name}.java"
                        ),
                        "language": "java",
                        "content": content
                    }
                ],
                "classes": [
                    {
                        "name": class_name,
                        "source_symbol": primary.get("name"),
                        "responsibility": "Dry-run skeleton for validation."
                    }
                ],
                "methods": [],
                "notes": [
                    "Dry-run backend did not call an LLM.",
                    "Use a LangChain backend for real Java generation."
                ],
                "unresolved_items": [
                    "Implementation requires model-backed generation."
                ]
            }
        }

    def _java_class_name(self, pascal_name):
        if pascal_name.startswith("T") and len(pascal_name) > 1:
            pascal_name = pascal_name[1:]

        cleaned = "".join(
            character
            for character in pascal_name
            if character.isalnum()
        )

        return cleaned[:1].upper() + cleaned[1:] if cleaned else "Migration"

    def _package_name(self, file_name):
        if not file_name:
            return "org.doublecmd.migration"

        normalized = str(file_name).replace("\\", "/").lower()

        if "filesources" in normalized:
            return "org.doublecmd.filesources"

        if "plugins" in normalized:
            return "org.doublecmd.plugins"

        return "org.doublecmd.migration"


class LangChainCodeGenerationBackend:
    """
    Backend that invokes a LangChain-compatible chat model.
    """

    backend_name = "langchain"

    def __init__(self, model=None):
        load_env_file()
        self.model_name = model or DEFAULT_LANGCHAIN_GENERATION_MODEL
        self.model = self._resolve_model(self.model_name)

    def generate(self, prompt_package):
        messages = list(prompt_package.get("prompt", {}).get("messages", []))

        if not messages:
            raise ValueError("Prompt package does not contain messages.")

        messages[-1] = dict(messages[-1])
        messages[-1]["content"] = (
            messages[-1]["content"]
            + "\n\n"
            + GENERATION_FORMAT_INSTRUCTIONS
        )

        response = self.model.invoke(messages)
        raw_content = getattr(response, "content", response)
        raw_output = raw_content

        if not isinstance(raw_output, str):
            raw_output = str(raw_output)

        return {
            "backend": self.backend_name,
            "raw_output": raw_output,
            "structured_output": self._parse_output(raw_content)
        }

    def _resolve_model(self, model):
        if isinstance(model, str):
            from langchain.chat_models import init_chat_model

            try:
                return init_chat_model(model)
            except ImportError as error:
                if model.startswith("google_genai:"):
                    raise ImportError(GOOGLE_GENAI_PACKAGE_HINT) from error

                raise

        return model

    def _parse_output(self, raw_output):
        parsed = self._parse_json_payload(raw_output)
        raw_text = raw_output if isinstance(raw_output, str) else str(raw_output)

        if isinstance(parsed, dict):
            normalized_source = self._generation_payload(parsed)
            java_file = self._java_source_from_raw_output(raw_text)

            if (
                not self._file_candidates(normalized_source)
                and java_file
                and not self._has_json_fence(raw_text)
            ):
                return {
                    "files": [java_file],
                    "classes": [],
                    "methods": [],
                    "notes": [
                        "Model returned Java source without the requested JSON "
                        "schema; source was wrapped into a generated file record."
                    ],
                    "unresolved_items": [
                        "Review generated file path and metadata because the "
                        "model did not return structured JSON."
                    ]
                }

            return self._normalize_structured_output(parsed)

        java_file = self._java_source_from_raw_output(raw_text)

        if java_file:
            return {
                "files": [java_file],
                "classes": [],
                "methods": [],
                "notes": [
                    "Model returned Java source without the requested JSON "
                    "schema; source was wrapped into a generated file record."
                ],
                "unresolved_items": [
                    "Review generated file path and metadata because the model "
                    "did not return structured JSON."
                ]
            }

        return {
            "files": [],
            "classes": [],
            "methods": [],
            "notes": [
                "Model returned non-JSON output; raw_output contains the full response."
            ],
            "unresolved_items": [
                "Parse model output into structured migration artifacts."
            ]
        }

    def _parse_json_payload(self, raw_output):
        """
        Parse model JSON even when the model wraps it in prose or fences.

        Chat models often return valid JSON inside a markdown ```json block or
        with a short introductory sentence. The validator needs the structured
        payload. Provider integrations can also return a list of content blocks,
        for example [{"type": "text", "text": "{...}"}]. This method tries the
        explicit text blocks first, then strict JSON, fenced JSON, and finally
        the first decodable JSON object embedded anywhere in the response.
        """

        candidates = self._candidate_texts(raw_output)

        for candidate in candidates:
            parsed = self._load_json_candidate(candidate)

            if parsed is not None:
                return parsed

        for candidate in candidates:
            parsed = self._embedded_json_object(candidate)

            if parsed is not None:
                return parsed

        return None

    def _candidate_texts(self, raw_output):
        texts = []
        self._append_text_candidate(texts, raw_output)

        if isinstance(raw_output, str):
            parsed_literal = self._literal_content_blocks(raw_output)

            if parsed_literal is not None:
                self._append_text_candidate(texts, parsed_literal)

        candidates = []

        for text in texts:
            stripped = text.strip()

            if stripped:
                candidates.append(stripped)
                candidates.extend(self._fenced_json_candidates(stripped))

        return self._dedupe(candidates)

    def _append_text_candidate(self, texts, value):
        if isinstance(value, str):
            texts.append(value)
            return

        if isinstance(value, dict):
            for key in ["text", "content", "output", "response"]:
                nested = value.get(key)

                if isinstance(nested, (str, list, dict)):
                    self._append_text_candidate(texts, nested)

            return

        if isinstance(value, list):
            for item in value:
                self._append_text_candidate(texts, item)

    def _literal_content_blocks(self, raw_output):
        stripped = raw_output.strip()

        if not (
            stripped.startswith("[")
            or stripped.startswith("{")
        ):
            return None

        try:
            return ast.literal_eval(stripped)
        except (SyntaxError, ValueError):
            return None

    def _dedupe(self, values):
        seen = set()
        deduped = []

        for value in values:
            if value in seen:
                continue

            seen.add(value)
            deduped.append(value)

        return deduped

    def _load_json_candidate(self, candidate):
        normalized = self._strip_json_language_prefix(candidate)

        for current in [normalized, self._repair_json_candidate(normalized)]:
            try:
                return json.loads(current)
            except json.JSONDecodeError:
                pass

        return None

    def _strip_json_language_prefix(self, candidate):
        stripped = candidate.strip()

        if stripped.lower().startswith("json"):
            remainder = stripped[4:].lstrip()

            if remainder.startswith("{") or remainder.startswith("["):
                return remainder

        return stripped

    def _repair_json_candidate(self, candidate):
        """
        Repair minor model-produced JSON mistakes without touching Java content.

        Gemini sometimes emits double-quoted JSON strings containing \\' for
        apostrophes. JSON does not define that escape sequence; replacing it
        with a literal apostrophe preserves the intended text.
        """

        return candidate.replace("\\'", "'")

    def _fenced_json_candidates(self, raw_output):
        pattern = re.compile(
            r"```(?:json)?\s*(.*?)```",
            re.IGNORECASE | re.DOTALL
        )

        return [
            match.group(1).strip()
            for match in pattern.finditer(raw_output)
        ]

    def _has_json_fence(self, raw_output):
        return bool(
            re.search(
                r"```\s*json\b",
                raw_output,
                re.IGNORECASE
            )
        )

    def _embedded_json_object(self, raw_output):
        decoder = json.JSONDecoder()

        for index, character in enumerate(raw_output):
            if character != "{":
                continue

            try:
                parsed, _ = decoder.raw_decode(raw_output[index:])
            except json.JSONDecodeError:
                repaired = self._repair_json_candidate(raw_output[index:])

                try:
                    parsed, _ = decoder.raw_decode(repaired)
                except json.JSONDecodeError:
                    continue

            if isinstance(parsed, dict):
                return parsed

        return None

    def _normalize_structured_output(self, output):
        normalized_source = self._generation_payload(output)
        files = self._normalize_files(normalized_source)
        notes = self._normalize_list(normalized_source.get("notes", []))
        unresolved_items = self._normalize_list(
            normalized_source.get("unresolved_items", [])
        )

        if not files:
            keys = ", ".join(sorted(str(key) for key in normalized_source))

            notes.append(
                "Parsed model JSON did not contain recognizable generated "
                f"files. Parsed keys: {keys or 'none'}."
            )
            unresolved_items.append(
                "Map model output into files[{path, language, content}] or "
                "adjust the generation prompt/schema."
            )

        return {
            "files": files,
            "classes": self._normalize_list(
                normalized_source.get("classes", [])
            ),
            "methods": self._normalize_list(
                normalized_source.get("methods", [])
            ),
            "notes": notes,
            "unresolved_items": unresolved_items
        }

    def _generation_payload(self, output):
        """
        Find the object that actually contains generated artifacts.

        Some models nest the requested schema under names such as
        structured_output, generation, output, or result. This keeps the public
        schema stable while accepting those harmless wrapper objects.
        """

        current = output
        wrapper_keys = [
            "structured_output",
            "generation",
            "output",
            "result",
            "migration",
            "response"
        ]

        for _ in range(5):
            if not isinstance(current, dict):
                return output

            if self._file_candidates(current):
                return current

            next_payload = None

            for key in wrapper_keys:
                nested = current.get(key)

                if isinstance(nested, dict):
                    next_payload = nested
                    break

            if next_payload is None:
                return current

            current = next_payload

        return current

    def _file_candidates(self, output):
        for key in [
            "files",
            "generated_files",
            "java_files",
            "source_files",
            "artifacts",
            "outputs"
        ]:
            if key in output:
                return output.get(key)

        if any(
            key in output
            for key in ["path", "file_path", "filename", "name", "content", "code"]
        ):
            return output

        return []

    def _normalize_files(self, output):
        candidates = self._file_candidates(output)

        if isinstance(candidates, dict):
            candidates = [candidates]

        if not isinstance(candidates, list):
            return []

        files = []

        for index, candidate in enumerate(candidates, start=1):
            normalized = self._normalize_file(candidate, index)

            if normalized:
                files.append(normalized)

        return files

    def _normalize_file(self, candidate, index):
        if isinstance(candidate, str):
            content = candidate.strip()

            if not content:
                return None

            return {
                "path": self._default_file_path(content, index),
                "language": "java",
                "content": content
            }

        if not isinstance(candidate, dict):
            return None

        content = self._first_string(
            candidate,
            ["content", "code", "source", "java", "body", "text"]
        )

        if not content:
            return None

        path = self._first_string(
            candidate,
            ["path", "file_path", "filepath", "filename", "file", "name"]
        )

        if not path or not path.endswith(".java") or "/" not in path:
            path = self._default_file_path(content, index, path)

        return {
            "path": path.replace("\\", "/"),
            "language": candidate.get("language") or "java",
            "content": content
        }

    def _first_string(self, mapping, keys):
        for key in keys:
            value = mapping.get(key)

            if isinstance(value, str) and value.strip():
                return value.strip()

        return None

    def _default_file_path(self, content, index=1, name_hint=None):
        package_name = self._package_name(content)
        class_name = self._class_name(content)

        if not class_name and name_hint:
            class_name = Path(name_hint).stem

        if not class_name:
            class_name = f"GeneratedMigration{index}"

        if package_name:
            return f"{package_name.replace('.', '/')}/{class_name}.java"

        return f"org/doublecmd/migration/{class_name}.java"

    def _package_name(self, content):
        match = re.search(
            r"^\s*package\s+([A-Za-z_][A-Za-z0-9_.]*)\s*;",
            content,
            re.MULTILINE
        )

        return match.group(1) if match else None

    def _class_name(self, content):
        match = re.search(
            r"\b(?:public\s+)?(?:class|interface|enum|record)\s+"
            r"([A-Za-z_][A-Za-z0-9_]*)",
            content
        )

        return match.group(1) if match else None

    def _normalize_list(self, value):
        if isinstance(value, list):
            return value

        if value:
            return [value]

        return []

    def _java_source_from_raw_output(self, raw_output):
        for candidate in self._fenced_code_candidates(raw_output):
            if self._looks_like_java(candidate):
                return {
                    "path": self._default_file_path(candidate),
                    "language": "java",
                    "content": candidate
                }

        stripped = raw_output.strip()

        if self._looks_like_java(stripped):
            return {
                "path": self._default_file_path(stripped),
                "language": "java",
                "content": stripped
            }

        return None

    def _fenced_code_candidates(self, raw_output):
        pattern = re.compile(
            r"```([A-Za-z0-9_-]+)?[ \t]*\n?(.*?)```",
            re.IGNORECASE | re.DOTALL
        )

        candidates = []

        for match in pattern.finditer(raw_output):
            language = (match.group(1) or "").lower()

            if language and language != "java":
                continue

            candidates.append(match.group(2).strip())

        return candidates

    def _looks_like_java(self, content):
        stripped = content.lstrip()

        if (
            stripped.startswith("{")
            or stripped.lower().startswith("json")
            or stripped.lower().startswith("```json")
        ):
            return False

        return bool(
            re.search(
                r"\b(class|interface|enum|record)\s+[A-Za-z_][A-Za-z0-9_]*",
                content
            )
        )


class GeneratedJavaFileWriter:
    """
    Persists generated Java file records under a controlled output directory.

    Model output is untrusted, so file paths are normalized and checked before
    writing. Absolute paths and parent-directory traversal are rejected instead
    of being resolved outside the requested output directory.
    """

    def write(
        self,
        generation_result,
        output_directory,
        overwrite=True,
        protected_paths=None,
        protected_type_names=None
    ):
        structured = self._structured_output(generation_result)
        root = Path(output_directory).resolve()
        files = structured.get("files", []) if isinstance(structured, dict) else []
        protected_paths = set(protected_paths or [])
        protected_type_names = set(protected_type_names or [])
        written = []
        skipped = []

        root.mkdir(parents=True, exist_ok=True)

        for index, file_record in enumerate(files):
            try:
                target = self._target_path(root, file_record)
            except ValueError as error:
                skipped.append({
                    "index": index,
                    "path": (
                        file_record.get("path")
                        if isinstance(file_record, dict)
                        else None
                    ),
                    "reason": str(error)
                })
                continue

            normalized_path = file_record.get("path", "").replace("\\", "/")
            type_name = target.stem

            if normalized_path in protected_paths:
                skipped.append({
                    "index": index,
                    "path": file_record.get("path"),
                    "reason": (
                        "Generated file path was already written by an "
                        "earlier batch job."
                    ),
                    "code": "batch_output_collision"
                })
                continue

            if type_name in protected_type_names:
                skipped.append({
                    "index": index,
                    "path": file_record.get("path"),
                    "reason": (
                        "Generated file declares a canonical shared support "
                        "type and should import the shared support contract "
                        "instead."
                    ),
                    "code": "shared_support_type"
                })
                continue

            if target.exists() and not overwrite:
                skipped.append({
                    "index": index,
                    "path": file_record.get("path"),
                    "reason": "File already exists and overwrite is disabled."
                })
                continue

            target.parent.mkdir(parents=True, exist_ok=True)
            target.write_text(
                file_record.get("content", ""),
                encoding="utf-8"
            )
            written.append({
                "path": file_record.get("path"),
                "absolute_path": str(target),
                "bytes": target.stat().st_size
            })

        return {
            "output_directory": str(root),
            "written": written,
            "skipped": skipped,
            "summary": {
                "written": len(written),
                "skipped": len(skipped)
            }
        }

    def _structured_output(self, generation_result):
        if not isinstance(generation_result, dict):
            return {}

        if "generation" in generation_result:
            return generation_result["generation"].get("structured_output", {})

        if "structured_output" in generation_result:
            return generation_result.get("structured_output", {})

        return generation_result

    def _target_path(self, root, file_record):
        if not isinstance(file_record, dict):
            raise ValueError("Generated file entry must be an object.")

        relative_path = file_record.get("path")
        content = file_record.get("content")

        if not relative_path or not isinstance(relative_path, str):
            raise ValueError("Generated file is missing a relative path.")

        if content is None or not isinstance(content, str):
            raise ValueError("Generated file is missing string content.")

        normalized = relative_path.replace("\\", "/")
        candidate = Path(normalized)

        if candidate.is_absolute() or ".." in candidate.parts:
            raise ValueError("Generated file path must be a safe relative path.")

        if candidate.suffix != ".java":
            raise ValueError("Generated file path must end with .java.")

        target = (root / candidate).resolve()

        if root != target and root not in target.parents:
            raise ValueError("Generated file path escapes output directory.")

        return target


def write_generated_java_files(
    generation_result,
    output_directory,
    overwrite=True,
    protected_paths=None,
    protected_type_names=None
):
    """
    Convenience wrapper for persisting generated Java files.
    """

    return GeneratedJavaFileWriter().write(
        generation_result,
        output_directory,
        overwrite=overwrite,
        protected_paths=protected_paths,
        protected_type_names=protected_type_names
    )


class ModernizationCodeGenerator:
    """
    End-to-end prompt plus code-generation orchestrator.
    """

    def __init__(
        self,
        repository,
        backend=None,
        prompt_generator=None,
        context_options=None
    ):
        self.repository = repository
        self.backend = backend or DryRunCodeGenerationBackend()
        self.prompt_generator = prompt_generator or ModernizationPromptGenerator(
            repository,
            context_options=context_options
        )

    def generate(
        self,
        task,
        target_language="Java",
        limit=5,
        graph_depth=1,
        document_types=None,
        include_source=True,
        max_source_lines=160,
        validate=False,
        compile_validation=False,
        output_directory=None,
        overwrite=True
    ):
        prompt_package = self.prompt_generator.generate(
            task,
            target_language=target_language,
            limit=limit,
            graph_depth=graph_depth,
            document_types=document_types,
            include_source=include_source,
            max_source_lines=max_source_lines
        )
        generation = self.backend.generate(prompt_package)

        if validate:
            generation["validation"] = validate_generated_code(
                generation,
                compile_sources=compile_validation
            )

        if output_directory:
            generation["written_files"] = write_generated_java_files(
                generation,
                output_directory,
                overwrite=overwrite
            )

        return {
            "task": {
                "description": task,
                "target_language": target_language
            },
            "prompt": prompt_package["prompt"],
            "context": prompt_package["context"],
            "generation": generation
        }


def load_env_file(env_file=".env", override=False):
    """
    Load API credentials from a .env file when python-dotenv is installed.

    Environment variables already set in the shell win by default. This keeps
    CI and explicit terminal configuration from being overwritten by local
    development files.
    """

    try:
        from dotenv import load_dotenv
    except ImportError:
        return False

    if env_file:
        path = Path(env_file)

        if path.exists():
            return bool(load_dotenv(path, override=override))

    return bool(load_dotenv(override=override))


def parse_args():
    parser = argparse.ArgumentParser(
        description="Generate Java modernization output using an LLM backend."
    )
    parser.add_argument(
        "task",
        help="Modernization task or natural-language query."
    )
    parser.add_argument(
        "--input",
        default="output",
        help="Directory containing generated repository JSON artifacts."
    )
    parser.add_argument(
        "--artifacts",
        default="output/embeddings",
        help="Directory containing embedding artifacts."
    )
    parser.add_argument(
        "--chroma",
        default="output/chroma",
        help="Persistent ChromaDB directory."
    )
    parser.add_argument(
        "--summaries",
        default="output/summaries",
        help="Directory containing generated summaries."
    )
    parser.add_argument(
        "--source-root",
        default="doublecmd",
        help="Root directory for source files referenced by metadata."
    )
    parser.add_argument(
        "--backend",
        choices=["dry-run", "langchain"],
        default="dry-run",
        help="Generation backend."
    )
    parser.add_argument(
        "--model",
        default=DEFAULT_LANGCHAIN_GENERATION_MODEL,
        help=(
            "LangChain model string for --backend langchain. "
            f"Default: {DEFAULT_LANGCHAIN_GENERATION_MODEL}"
        )
    )
    parser.add_argument(
        "--env-file",
        default=".env",
        help="Optional .env file to load before initializing the model."
    )
    parser.add_argument(
        "--types",
        nargs="*",
        choices=["unit", "class", "method", "subsystem"],
        default=None,
        help="Optional document types to include."
    )
    parser.add_argument(
        "--limit",
        type=int,
        default=5,
        help="Maximum retrieval results from each retrieval layer."
    )
    parser.add_argument(
        "--graph-depth",
        type=int,
        default=1,
        help="Graph expansion depth."
    )
    parser.add_argument(
        "--max-source-lines",
        type=int,
        default=160,
        help="Maximum source lines per extracted source item."
    )
    parser.add_argument(
        "--no-source",
        action="store_true",
        help="Skip source extraction."
    )
    parser.add_argument(
        "--validate",
        action="store_true",
        help="Validate generated Java output before printing."
    )
    parser.add_argument(
        "--compile-validation",
        action="store_true",
        help="Also compile generated Java with javac during validation."
    )
    parser.add_argument(
        "--output-directory",
        help="Persist generated Java files under this directory."
    )
    parser.add_argument(
        "--no-overwrite",
        action="store_true",
        help="Do not overwrite existing generated Java files."
    )
    parser.add_argument(
        "--json",
        action="store_true",
        help="Print full generation package as JSON."
    )

    return parser.parse_args()


def main():
    args = parse_args()
    load_env_file(args.env_file)

    repository = Repository(
        load_repository(args.input)
    )
    try:
        backend = (
            LangChainCodeGenerationBackend(args.model)
            if args.backend == "langchain"
            else DryRunCodeGenerationBackend()
        )
    except ImportError as error:
        raise SystemExit(str(error)) from error
    generator = ModernizationCodeGenerator(
        repository,
        backend=backend,
        context_options={
            "artifacts_directory": args.artifacts,
            "persist_directory": args.chroma,
            "summary_directory": args.summaries,
            "source_root": args.source_root
        }
    )
    result = generator.generate(
        args.task,
        limit=args.limit,
        graph_depth=args.graph_depth,
        document_types=args.types,
        include_source=not args.no_source,
        max_source_lines=args.max_source_lines,
        validate=args.validate or args.compile_validation,
        compile_validation=args.compile_validation,
        output_directory=args.output_directory,
        overwrite=not args.no_overwrite
    )

    if args.json:
        print(json.dumps(result, indent=2, sort_keys=True))
    else:
        structured = result["generation"]["structured_output"]

        for file_record in structured.get("files", []):
            print(f"File: {file_record.get('path')}")
            print(file_record.get("content", ""))
            print()

        if structured.get("notes"):
            print("Notes:")
            for note in structured["notes"]:
                print(f"- {note}")

        validation = result["generation"].get("validation")

        if validation:
            print("Validation:")
            print(f"- status: {validation['status']}")
            print(f"- errors: {validation['summary']['errors']}")
            print(f"- warnings: {validation['summary']['warnings']}")

            for finding in validation["findings"]:
                location = (
                    f" [{finding['file']}]"
                    if "file" in finding
                    else ""
                )
                print(
                    f"- {finding['severity']} {finding['code']}"
                    f"{location}: {finding['message']}"
                )

        written_files = result["generation"].get("written_files")

        if written_files:
            print("Written files:")
            print(f"- output_directory: {written_files['output_directory']}")
            print(f"- written: {written_files['summary']['written']}")
            print(f"- skipped: {written_files['summary']['skipped']}")

            for file_record in written_files["written"]:
                print(f"- {file_record['absolute_path']}")

            for skipped in written_files["skipped"]:
                print(
                    f"- skipped {skipped.get('path')}: "
                    f"{skipped.get('reason')}"
                )


if __name__ == "__main__":
    main()
